[features]
seeds = false
[programs.devnet]
dice = "77WPfiSfVcYHZQKNUZH6wbB6v1dXieX4upy2UuTMGSj2"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/ubuntu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
